export interface ConsumerBusinessDetails
{
    firstname:String,
    lastname:String,
    dob:String,
    businessname:String,
    pandetails:String,
    email:String,
    phone:String,
    website:String,
    businessoverview:String,
    validity:String,
    agentname:String,
    agentid:number,
    businessid:number,
    consumerId:number,
    businesscategory:String,
    businesstype:String,
    businessturnover:number,
    capitalinvested:number,
    totalemployees:number,
    businessvalue:number,
    businessage:number
}